version: "3.9"
services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - ./data:/data/
    env_file: .env
