storage:
  type: sqlite
  path: /data/data.db

alerting:
  discord:
    webhook-url: ${DISCORD_WEBHOOK}

endpoints:
  # Physical Servers
  - name: Mercury
    group: Servers
    url: "icmp://${MERCURY}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Mercury is Down"
        send-on-resolved: true

  - name: Pantheon
    group: Servers
    url: "icmp://${PANTHEON}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Pantheon is Down"
        send-on-resolved: true

  - name: Poseidon
    group: Servers
    url: "icmp://${POSEIDON}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Poseidon is Down"
        send-on-resolved: true

  - name: Zeus
    group: Servers
    url: "icmp://${ZEUS}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Zeus is Down"
        send-on-resolved: true

  - name: Hades
    group: Servers
    url: "icmp://${HADES}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Hades is Down"
        send-on-resolved: true

  - name: Remus
    group: Servers
    url: "icmp://${REMUS}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Remus is Down"
        send-on-resolved: true

  # Media Server Components
  - name: SabNZBd
    group: Media Server
    url: "https://sabnzbd${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "SabNZBd is Down"
        send-on-resolved: true

  - name: Prowlarr
    group: Media Server
    url: "https://prowlarr${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Prowlarr is Down"
        send-on-resolved: true

  - name: Sonarr
    group: Media Server
    url: "https://sonarrhd${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Sonarr is Down"
        send-on-resolved: true

  - name: Radarr
    group: Media Server
    url: "https://radarrhd${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Radarr is Down"
        send-on-resolved: true

  - name: Overseerr
    group: Media Server
    url: "https://requests${DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Overseerr is Down"
        send-on-resolved: true

  - name: Tautulli
    group: Media Server
    url: "https://mediastats${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Tautulli is Down"
        send-on-resolved: true

  - name: Tdarr
    group: Media Server
    url: "https://tdarr${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Tdarr is Down"
        send-on-resolved: true

  - name: Plex
    group: Media Server
    url: "https://plex${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Plex is Down"
        send-on-resolved: true

  # Networking Services
  - name: Adguard Home
    group: Networking Services
    url: "tcp://${AD_GUARD}:53"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Adguard Home is Down"
        send-on-resolved: true

  - name: Bind DNS
    group: Networking Services
    url: "tcp://${INT_DOCKERHOST_01}:53"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Bind DNS is Down"
        send-on-resolved: true

  - name: Internal Nginx Proxy Manager
    group: Networking Services
    url: "tcp://${INT_DOCKERHOST_01}:81"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Internal NPM is Down"
        send-on-resolved: true

  - name: External Nginx Proxy Manager
    group: Networking Services
    url: "tcp://${EXT_DOCKERHOST_01}:80"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Internal NPM is Down"
        send-on-resolved: true

  # Network Equipment
  - name: UDM Pro
    group: Network Equipment
    url: "icmp://${FW}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "UDM Pro is Down"
        send-on-resolved: true

  - name: Standard 24 Switch
    group: Network Equipment
    url: "icmp://${SW1_24}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Standard 24 Switch is Down"
        send-on-resolved: true

  - name: Enterprise 24 PoE Switch
    group: Network Equipment
    url: "icmp://${SW2_24POE}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Enterprise 24 PoE Switch is Down"
        send-on-resolved: true

  - name: Ceph Switch
    group: Network Equipment
    url: "icmp://${SW3_10GB}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Ceph Switch is Down"
        send-on-resolved: true

  - name: AP Switch
    group: Network Equipment
    url: "icmp://${SW4_AP}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "AP Switch is Down"
        send-on-resolved: true

  - name: Camera Switch
    group: Network Equipment
    url: "icmp://${SW5_CAMS}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Camera Switch is Down"
        send-on-resolved: true

  - name: Upstairs AP
    group: Network Equipment
    url: "icmp://${AP1}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Upstairs AP is Down"
        send-on-resolved: true

  - name: Family Room AP
    group: Network Equipment
    url: "icmp://${AP2}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Family Room AP is Down"
        send-on-resolved: true

  - name: Living Room AP
    group: Network Equipment
    url: "icmp://${AP4}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Living Room AP is Down"
        send-on-resolved: true

  - name: Basement AP
    group: Network Equipment
    url: "icmp://${AP3}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Basement AP is Down"
        send-on-resolved: true
