storage:
  type: sqlite
  path: /data/data.db

alerting:
  discord:
    webhook-url: ${DISCORD_WEBHOOK}

endpoints:
  # Physical Servers
  - name: Mercury
    group: Servers
    url: "icmp://${MERCURY}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Pantheon
    group: Servers
    url: "icmp://${PANTHEON}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Poseidon
    group: Servers
    url: "icmp://${POSEIDON}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Zeus
    group: Servers
    url: "icmp://${ZEUS}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Hades
    group: Servers
    url: "icmp://${HADES}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Remus
    group: Servers
    url: "icmp://${REMUS}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  # Media Server Components
  - name: SabNZBd
    group: Media Server
    url: "https://sabnzbd${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Prowlarr
    group: Media Server
    url: "https://prowlarr${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Sonarr
    group: Media Server
    url: "https://sonarrhd${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Radarr
    group: Media Server
    url: "https://radarrhd${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Overseerr
    group: Media Server
    url: "https://requests${DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
