storage:
  type: sqlite
  path: /data/data.db

alerting:
  discord:
    webhook-url: ${DISCORD_WEBHOOK}

endpoints:
  # Physical Servers
  - name: Mercury
    group: Servers
    url: "icmp://${MERCURY}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Mercury is Down"
        send-on-resolved: true

  - name: Pantheon
    group: Servers
    url: "icmp://${PANTHEON}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Pantheon is Down"
        send-on-resolved: true

  - name: Poseidon
    group: Servers
    url: "icmp://${POSEIDON}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Poseidon is Down"
        send-on-resolved: true

  - name: Zeus
    group: Servers
    url: "icmp://${ZEUS}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Zeus is Down"
        send-on-resolved: true

  - name: Hades
    group: Servers
    url: "icmp://${HADES}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Hades is Down"
        send-on-resolved: true

  - name: Remus
    group: Servers
    url: "icmp://${REMUS}"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        descripton: "Remus is Down"
        send-on-resolved: true

  # Media Server Components
  - name: SabNZBd
    group: Media Server
    url: "https://sabnzbd${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "SabNZBd is Down"
        send-on-resolved: true

  - name: Prowlarr
    group: Media Server
    url: "https://prowlarr${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Prowlarr is Down"
        send-on-resolved: true

  - name: Sonarr
    group: Media Server
    url: "https://sonarrhd${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Sonarr is Down"
        send-on-resolved: true

  - name: Radarr
    group: Media Server
    url: "https://radarrhd${LOCAL_DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Radarr is Down"
        send-on-resolved: true

  - name: Overseerr
    group: Media Server
    url: "https://requests${DOMAIN}"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        descripton: "Overseerr is Down"
        send-on-resolved: true
